Remove stylelint vulnerable dependency
openshift/console-dashboards-plugin pull request #15
Opened 2023-07-11 08:39 UTC by jgbernalp

This PR removes stylelint as it brings many vulnerable dependencies. The plugin does not use CSS so it wont affect any functionality. If we include CSS in the future we can evaluate if the CSS lint is necessary.

2023-07-11 08:59 UTC, kyoto requested changes
Could you please also add your (very helpful) PR description to the commit message?

2023-07-11 10:04 UTC, kyoto approved these changes
/lgtm

2023-07-13 12:07 UTC, zhuje commented
/lgtm

2023-07-13 14:14 UTC, zhuje approved these changes

2023-07-13 15:47 UTC, merged